name: External Issue Form
description: "**EXTERNAL** Please use this form if you are not part of the finance team."
assignees:
  - Dillon-DellAquila
body:
  - type: dropdown
    id: priority
    attributes:
      label: Select the priority of this issue
      multiple: false
      options:
        - Urgent (Needs to be done today)
        - High (Within the next couple days)
        - Medium (Within the week)
        - Low (Within the month)
        - Backlog (no set due date, use to keep track of ongoing tasks)
    validations:
      required: true

  - type: dropdown
    id: workstream_to
    attributes:
      label: What Finance team will work on this?
      description: Please select the team that will be working on this issue
      multiple: true
      options:
        - Business Insights
        - Capital Management
        - Claims
        - Ember
        - Expense Management
        - FP&A
        - Investor Relations
        - Product
        - Production
        - Sigma
        - Other/Not sure
    validations:
      required: true

  - type: input
    id: workstream_to_other
    attributes:
      label: If you selected "Other/Not sure" above, please specify
      description: _(Optional)_

  - type: dropdown
    id: workstream_from
    attributes:
      label: Requesting Workstream
      description: Please select which workstream is requesting this issue
      multiple: true
      options:
        - Agency
        - Claims
        - Data
        - Ember
        - Executive
        - Investor Relations
        - Legal
        - Marketing
        - People Team
        - Production
        - Other
    validations:
      required: true

  - type: input
    id: workstream_from_other
    attributes:
      label: If you selected "Other" above, please specify your workstream
      description: _(Optional)_

  - type: dropdown
    id: type
    attributes:
      label: Type of Issue
      multiple: false
      options:
        - Bug Fix
        - Improvement
        - Recurring Reporting
        - Request
        - Other
    validations:
      required: true

  - type: input
    id: type_other
    attributes:
      label: If you selected "Other" above, please specify the type of issue
      description: _(Optional)_

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please add a brief description of the work that needs to be done
    validations:
      required: true
