name: External Issue Form
description: Please fill out this form to file an issue that was raised by an **external** staekholder.
assignees: 
  - Dillon-DellAquila
body:
  - type: dropdown
    id: priority
    attributes:
      label: Select the priority of this issue
      multiple: false
      options:
        - Urgent (Needs to be done today)
        - High (Within the next couple days)
        - Medium (Withing the month)
        - Low (Can be added to backlog, no strict due date)
    validations:
      required: true
  - type: dropdown
    id: internal_external
    attributes:
      label: Did this request come from or is it for someone outside of the Finance team?
      multiple: false
      options:
        - Yes (External Request)
        - No (Internal Request)
    validations:
      required: true
  - type: dropdown
    id: workstream
    attributes:
      label: Workstream
      description: Please select which workstreams are involved in this issue
      multiple: true
      options:
        - Agency
        - Branch Claims Model
        - Delphi
        - Domo
        - Ember
        - Expense Forecasting
        - Forecasting/Planning
        - Investor Relations
        - Metric Reporting
        - Regulatory
        - Sigma
        - Other, please list in the next section
    validations:
      required: true
  - type: input
    id: workstream_other
    attributes:
      label: If selected Other, please add the type of issue
      description: _(Optional)_
  - type: dropdown
    id: type
    attributes:
      label: Type of Issue
      multiple: false
      options:
        - Bug Fix
        - Improvement
        - Recurring Reporting
        - Request
        - Other
    validations:
      required: true
  - type: input
    id: type_other
    attributes:
      label: If selected Other, please add the type of issue
      description: _(Optional)_
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Please add a brief description of the work that needs to be done
    validations:
      required: true
  - type: markdown
    attributes:
      value: >
        <br />
  - type: markdown
    attributes:
      value: >
        **Please assign this issue to yourself or someone who will be working on the issue❗❗❗**
